In [1]:
import pandas as pd

data = {
    "Product": ["Notebook", "Pen", "Bag"],
    "Price": [50, 10, 300],
    "Quantity": [3, 10, 1]
}

df = pd.DataFrame(data)

df

    Product  Price  Quantity
0  Notebook     50         3
1       Pen     10        10
2       Bag    300         1

In [2]:
df["Total"] = df["Price"] * df["Quantity"]
df

    Product  Price  Quantity  Total
0  Notebook     50         3    150
1       Pen     10        10    100
2       Bag    300         1    300

In [3]:
df.describe()

            Price   Quantity       Total
count    3.000000   3.000000    3.000000
mean   120.000000   4.666667  183.333333
std    157.162336   4.725816  104.083300
min     10.000000   1.000000  100.000000
25%     30.000000   2.000000  125.000000
50%     50.000000   3.000000  150.000000
75%    175.000000   6.500000  225.000000
max    300.000000  10.000000  300.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Product   3 non-null      object
 1   Price     3 non-null      int64
 2   Quantity  3 non-null      int64
 3   Total     3 non-null      int64
dtypes: int64(3), object(1)
memory usage: 228.0+ bytes